### ISSUE TITLE
Implement these tips to help prevent accidental commit of sensitive data 

### ISSUE THREAD

**Issue by jsphdms** [jsphdms/opendatascot#43]
https://github.com/ukgovdatascience/dotfiles

**Comment by thomascrines** [comment]
I was just looking at this one, and wondered if it might not be necessary? The main purpose seems to be to prevent data files being uploaded to the remote repo, but as we're working directly from the open data platform it seems to me that we would never have any data files in the project, and if we did they would be of publicly available data. If there's something I've missed let me know and I'll update the gitignore, and there's another step to create pre-commit hooks that we would each need to do on our individual machines
